#
# Config for Site
#
# Run with 'bundle exec jekyll serve'
#

# Name and Description of Site
title: Grimhook
description: Grimhook is a first-person action platformer about a nautical warrior facing down an army of robots. Use your complex and unconventional movement abilities to traverse through a sunken city; grapple, bounce, and dash your way through hoards of automata on your way to the city's peak.
url: https://grimhook.com

# Plugins
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]

permalink: /:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
